import type { Metadata } from "next";
import { DM_Sans, Habibi } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import AppSetup from "./appSetup";

const geistSans = DM_Sans({
	variable: "--font-heading",
	subsets: ["latin"],
});

const geistMono = Habibi({
	weight: "400",
	variable: "--font-text",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<AppSetup>{children}</AppSetup>
			</body>
		</html>
	);
}
